export const companyTickerMap = {
  'Bharti Airtel Ltd': 'BHARTIARTL',
  'Vedanta Ltd': 'VEDL',
  'IDBI Bank Ltd': 'IDBI',
  'Varun Beverages Ltd': 'VBL',
  'Cipla Ltd': 'CIPLA',
  'GAIL (India) Ltd': 'GAIL',
  'Waaree Energies Ltd': 'WAAREEENER',
  'Indus Towers Ltd': 'INDUSTOWER',
  'Bharti Hexacom Ltd': 'BHARTIHEXA',
  'Ashok Leyland Ltd': 'ASHOKLEY',
  'Torrent Power Ltd': 'TORNTPOWER',
  'Bharat Electronics Ltd': 'BEL',
  'TVS Motor Company Ltd': 'TVSMOTOR',
  'Maruti Suzuki India Ltd': 'MARUTI',
  'Sun Pharmaceutical Industries Ltd': 'SUNPHARMA',
  'Wipro Ltd': 'WIPRO',
  'Tech Mahindra Ltd': 'TECHM',
  'Bank of Baroda': 'BANKBARODA',
  'Solar Industries India Ltd': 'SOLARINDS',
  'Torrent Pharmaceuticals Ltd': 'TORNTPHARM',
  'Lodha Developers Ltd': 'LODHA',
  'Mazagon Dock Shipbuilders Ltd': 'MAZDOCK',
  'Hero MotoCorp Ltd': 'HEROMOTOCO',
  'ABB India Ltd': 'ABB',
  'Indian Hotels Co Ltd': 'INDHOTEL',
  'Vodafone Idea Ltd': 'IDEA',
  'Indian Overseas Bank': 'IOB',
  'FSN E-Commerce Ventures Ltd': 'NYKAA',
  'Suzlon Energy Ltd': 'SUZLON',
  'Vishal Mega Mart Ltd': 'VMM',
  'ICICI Bank Ltd': 'ICICIBANK',
  'State Bank of India': 'SBIN',
  'Life Insurance Corporation of India': 'LICI',
  'NTPC Ltd': 'NTPC',
  'Hindustan Aeronautics Ltd': 'HAL',
  'Adani Ports': 'ADANIPORTS',
  'DLF Ltd': 'DLF',
  'SBI Life Insurance Company Ltd': 'SBILIFE',
  'Trent Ltd': 'TRENT',
  'HDFC Life Insurance Company Ltd': 'HDFCLIFE',
  'Pidilite Industries Ltd': 'PIDILITIND',
  'Power Finance Corporation Ltd': 'PFC',
  'HDFC AMC Ltd': 'HDFCAMC',
  'Canara Bank': 'CANBK',
  'Siemens Ltd': 'SIEMENS',
  'Cummins India Ltd': 'CUMMINSIND',
  'Indian Bank': 'INDIANB',
  'Union Bank of India': 'UNIONBANK',
  'BSE Ltd': 'BSE',
  'ICICI Lombard': 'ICICIGI',
  'Zydus Lifesciences Ltd': 'ZYDUSLIFE',
  'United Spirits Ltd': 'UNITDSPR',
  'REC Ltd': 'RECLTD',
  'Persistent Systems Ltd': 'PERSISTENT',
  'Lupin Ltd': 'LUPIN',
  'Bharat Heavy Electricals Ltd': 'BHEL',
  'Hitachi Energy India Ltd': 'POWERINDIA',
  'GE Vernova T&D India Ltd': 'GVT&D',
  'PB Fintech Ltd': 'POLICYBZR',
  'Yes Bank Ltd': 'YESBANK',
  'Godrej Properties Ltd': 'GODREJPROP',
  'General Insurance Corp. of India': 'GICRE',
  'Oberoi Realty Ltd': 'OBEROIRLTY',
  'Bharat Forge Ltd': 'BHARATFORG',
  'AU Small Finance Bank Ltd': 'AUBANK',
  'UPL Ltd': 'UPL',
  'Bank of India': 'BANKINDIA',
  'Max Financial Services Ltd': 'MFSL',
  'L&T Finance Ltd': 'LTF',
  'Tata Consultancy Services Ltd': 'TCS',
  'Infosys Ltd': 'INFY',
  'Mahindra & Mahindra Ltd': 'M&M',
  'Axis Bank Ltd': 'AXISBANK',
  'Eternal Ltd': 'ETERNAL',
  'Adani Power Ltd': 'ADANIPOWER',
  'Hindustan Zinc Ltd': 'HINDZINC',
  'Hyundai Motor India Ltd': 'HYUNDAI',
  'Indian Railway Finance Corporation Ltd': 'IRFC',
  'Punjab National Bank': 'PNB',
  'Godrej Consumer Products Ltd': 'GODREJCP',
  'Apollo Hospitals Enterprise Ltd': 'APOLLOHOSP',
  'LG Electronics India Ltd': 'LGEINDIA',
  'Polycab India Ltd': 'POLYCAB',
  'Adani Energy Solutions Ltd': 'ADANIENSOL',
  'Samvardhana Motherson International Ltd': 'MOTHERSON',
  'Dixon Technologies (India) Ltd': 'DIXON',
  'SRF Ltd': 'SRF',
  'Havells India Ltd': 'HAVELLS',
  'Bajaj Housing Finance Ltd': 'BAJAJHFL',
  'ICICI Prudential Life Insurance Co Ltd': 'ICICIPRULI',
  'NTPC Green Energy Ltd': 'NTPCGREEN',
  'Oracle Financial Services Software Ltd': 'OFSS',
  'Alkem Laboratories Ltd': 'ALKEM',
  'Aurobindo Pharma Ltd': 'AUROPHARMA',
  'Abbott India Ltd': 'ABBOTINDIA',
  'Colgate-Palmolive (India) Ltd': 'COLPAL',
  'JSW Infrastructure Ltd': 'JSWINFRA',
  'Steel Authority of India Ltd': 'SAIL',
  'Glenmark Pharmaceuticals Ltd': 'GLENMARK',
  'Linde India Ltd': 'LINDEINDIA',
  'Mphasis Ltd': 'MPHASIS',
  'Shriram Finance Ltd': 'SHRIRAMFIN',
  'Bajaj Finance Ltd': 'BAJFINANCE',
  'HDFC Bank Ltd': 'HDFCBANK',
  'Larsen & Toubro Ltd': 'LT',
  'ITC Ltd': 'ITC',
  'HCL Technologies Ltd': 'HCLTECH',
  'Coal India Ltd': 'COALINDIA',
  'Interglobe Aviation Ltd': 'INDIGO',
  'Tata Steel Ltd': 'TATASTEEL',
  'Eicher Motors Ltd': 'EICHERMOT',
  'Adani Green Energy Ltd': 'ADANIGREEN',
  'Tata Motors Passenger Vehicles Ltd': 'TMPV',
  'Muthoot Finance Ltd': 'MUTHOOTFIN',
  'Bosch Ltd': 'BOSCHLTD',
  'Shree Cement Ltd': 'SHREECEM',
  'Marico Ltd': 'MARICO',
  'Dabur India Ltd': 'DABUR',
  'Aditya Birla Capital Ltd': 'ABCAPITAL',
  'Lloyds Metals & Energy Ltd': 'LLOYDSME',
  'Oil India Ltd': 'OIL',
  'MRF Ltd': 'MRF',
  'Tube Investments of India Ltd': 'TIINDIA',
  'Motilal Oswal Financial Services Ltd': 'MOTILALOFS',
  'IDFC First Bank Ltd': 'IDFCFIRSTB',
  'Nippon Life India Asset Management Ltd': 'NAM-INDIA',
  'Tata Communications Ltd': 'TATACOMM',
  'Federal Bank Ltd': 'FEDERALBNK',
  'Reliance Industries Ltd': 'RELIANCE',
  'Kotak Mahindra Bank Ltd': 'KOTAKBANK',
  'Adani Enterprises Ltd': 'ADANIENT',
  'JSW Steel Ltd': 'JSWSTEEL',
  'Power Grid Corporation of India Ltd': 'POWERGRID',
  'Britannia Industries Ltd': 'BRITANNIA',
  'Bharat Petroleum Corporation Ltd': 'BPCL',
  'Ambuja Cements Ltd': 'AMBUJACEM',
  'Tata Power Company Ltd': 'TATAPOWER',
  'Tata Consumer Products Ltd': 'TATACONSUM',
  'Swiggy Ltd': 'SWIGGY',
  'Dr Reddys Laboratories Ltd': 'DRREDDY',
  'Hindustan Petroleum Corporation Ltd': 'HINDPETRO',
  'GMR Airports Ltd': 'GMRAIRPORT',
  'Prestige Estates Projects Ltd': 'PRESTIGE',
  'Uno Minda Ltd': 'UNOMINDA',
  'NMDC Ltd': 'NMDC',
  'Berger Paints India Ltd': 'BERGEPAINT',
  'Phoenix Mills Ltd': 'PHOENIXLTD',
  'Coforge Ltd': 'COFORGE',
  'Indian Railway Catering & Tourism Corp Ltd': 'IRCTC',
  'P I Industries Ltd': 'PIIND',
  'Kalyan Jewellers Ltd': 'KALYANKJIL',
  'Hindustan Unilever Ltd': 'HINDUNILVR',
  'Bajaj Finserv Ltd': 'BAJAJFINSV',
  'Oil & Natural Gas Corpn Ltd': 'ONGC',
  'Avenue Supermarts Ltd': 'DMART',
  'Bajaj Auto Ltd': 'BAJAJ-AUTO',
  'Asian Paints Ltd': 'ASIANPAINT',
  'Indian Oil Corporation Ltd': 'IOC',
  'Jio Financial Services Ltd': 'JIOFIN',
  'LTIMindtree Ltd': 'LTIM',
  'Bajaj Holdings & Investment Ltd': 'BAJAJHLDNG',
  'Tata Capital Ltd': 'TATACAP',
  'Cholamandalam Investment & Finance Co Ltd': 'CHOLAFIN',
  'CG Power & Industrial Solutions Ltd': 'CGPOWER',
  'Max Healthcare Institute Ltd': 'MAXHEALTH',
  'Jindal Steel Ltd': 'JINDALSTEL',
  'JSW Energy Ltd': 'JSWENERGY',
  'NHPC Ltd': 'NHPC',
  'Info Edge (India) Ltd': 'NAUKRI',
  'One 97 Communications Ltd': 'PAYTM',
  'Rail Vikas Nigam Ltd': 'RVNL',
  'Adani Total Gas Ltd': 'ATGL',
  'Jindal Stainless Ltd': 'JSL',
  'Coromandel International Ltd': 'COROMANDEL',
  'Schaeffler India Ltd': 'SCHAEFFLER',
  'HDB Financial Services Ltd': 'HDBFS',
  'IndusInd Bank Ltd': 'INDUSINDBK',
  'FACT Ltd': 'FACT',
  'Bharat Dynamics Ltd': 'BDL',
  'UltraTech Cement Ltd': 'ULTRACEMCO',
  'Titan Company Ltd': 'TITAN',
  'Nestle India Ltd': 'NESTLEIND',
  'Mankind Pharma Ltd': 'MANKIND',
  'SBI Cards & Payment Services Ltd': 'SBICARD',
  'Grasim Industries Ltd': 'GRASIM'
};
