// Comprehensive ticker mapping for Screener.in
// Includes both abbreviated and full company name variations
export const companyTickerMap = {
  // A
  'A B B': 'ABB',
  'ABB India Ltd': 'ABB',
  'Abbott India': 'ABBOTINDIA',
  'Abbott India Ltd': 'ABBOTINDIA',
  
  // Adani Group
  'Adani Energy Sol': 'ADANIENSOL',
  'Adani Energy Solutions Ltd': 'ADANIENSOL',
  'Adani Enterp.': 'ADANIENT',
  'Adani Enterprises Ltd': 'ADANIENT',
  'Adani Green': 'ADANIGREEN',
  'Adani Green Energy Ltd': 'ADANIGREEN',
  'Adani Ports': 'ADANIPORTS',
  'Adani Ports and Special Economic Zone Ltd': 'ADANIPORTS',
  'Adani Power': 'ADANIPOWER',
  'Adani Power Ltd': 'ADANIPOWER',
  'Adani Total Gas': 'ATGL',
  'Adani Total Gas Ltd': 'ATGL',
  
  // Aditya Birla
  'Aditya Birla Cap': 'ABCAPITAL',
  'Aditya Birla Capital Ltd': 'ABCAPITAL',
  
  // A
  'Alkem Lab': 'ALKEM',
  'Alkem Laboratories Ltd': 'ALKEM',
  'Ambuja Cements': 'AMBUJACEM',
  'Ambuja Cements Ltd': 'AMBUJACEM',
  'Apollo Hospitals': 'APOLLOHOSP',
  'Apollo Hospitals Enterprise Ltd': 'APOLLOHOSP',
  'Ashok Leyland': 'ASHOKLEY',
  'Ashok Leyland Ltd': 'ASHOKLEY',
  'Asian Paints': 'ASIANPAINT',
  'Asian Paints Ltd': 'ASIANPAINT',
  'AU Small Finance': 'AUBANK',
  'AU Small Finance Bank Ltd': 'AUBANK',
  'Aurobindo Pharma': 'AUROPHARMA',
  'Aurobindo Pharma Ltd': 'AUROPHARMA',
  'Avenue Super.': 'DMART',
  'Avenue Supermarts Ltd': 'DMART',
  'Axis Bank': 'AXISBANK',
  'Axis Bank Ltd': 'AXISBANK',
  
  // B
  'B H E L': 'BHEL',
  'Bharat Heavy Electricals Ltd': 'BHEL',
  'B P C L': 'BPCL',
  'Bharat Petroleum Corporation Ltd': 'BPCL',
  'Bajaj Auto': 'BAJAJ-AUTO',
  'Bajaj Auto Ltd': 'BAJAJ-AUTO',
  'Bajaj Finance': 'BAJFINANCE',
  'Bajaj Finance Ltd': 'BAJFINANCE',
  'Bajaj Finserv': 'BAJAJFINSV',
  'Bajaj Finserv Ltd': 'BAJAJFINSV',
  'Bajaj Holdings': 'BAJAJHLDNG',
  'Bajaj Holdings & Investment Ltd': 'BAJAJHLDNG',
  'Bajaj Housing': 'BAJAJHFL',
  'Bajaj Housing Finance Ltd': 'BAJAJHFL',
  'Bank of Baroda': 'BANKBARODA',
  'Bank of India': 'BANKINDIA',
  'Berger Paints': 'BERGEPAINT',
  'Berger Paints India Ltd': 'BERGEPAINT',
  'Bharat Dynamics': 'BDL',
  'Bharat Dynamics Ltd': 'BDL',
  'Bharat Electron': 'BEL',
  'Bharat Electronics Ltd': 'BEL',
  'Bharat Forge': 'BHARATFORG',
  'Bharat Forge Ltd': 'BHARATFORG',
  'Bharti Airtel': 'BHARTIARTL',
  'Bharti Airtel Ltd': 'BHARTIARTL',
  'Bharti Hexacom': 'BHARTIHEXA',
  'Bharti Hexacom Ltd': 'BHARTIHEXA',
  'Bosch': 'BOSCHLTD',
  'Bosch Ltd': 'BOSCHLTD',
  'Britannia Inds.': 'BRITANNIA',
  'Britannia Industries Ltd': 'BRITANNIA',
  'BSE': 'BSE',
  'BSE Ltd': 'BSE',
  
  // C
  'Canara Bank': 'CANBK',
  'CG Power & Ind': 'CGPOWER',
  'CG Power & Industrial Solutions Ltd': 'CGPOWER',
  'Cholaman.Inv.&Fn': 'CHOLAFIN',
  'Cholamandalam Investment & Finance Co Ltd': 'CHOLAFIN',
  'Cipla': 'CIPLA',
  'Cipla Ltd': 'CIPLA',
  'Coal India': 'COALINDIA',
  'Coal India Ltd': 'COALINDIA',
  'Coforge': 'COFORGE',
  'Coforge Ltd': 'COFORGE',
  'Colgate-Palmoliv': 'COLPAL',
  'Colgate-Palmolive (India) Ltd': 'COLPAL',
  'Coromandel Inter': 'COROMANDEL',
  'Coromandel International Ltd': 'COROMANDEL',
  'Cummins India': 'CUMMINSIND',
  'Cummins India Ltd': 'CUMMINSIND',
  
  // D
  'Dabur India': 'DABUR',
  'Dabur India Ltd': 'DABUR',
  'Dixon Technolog.': 'DIXON',
  'Dixon Technologies (India) Ltd': 'DIXON',
  'DLF': 'DLF',
  'DLF Ltd': 'DLF',
  'Dr Reddy\'s Labs': 'DRREDDY',
  'Dr Reddys Laboratories Ltd': 'DRREDDY',
  
  // E
  'Eicher Motors': 'EICHERMOT',
  'Eicher Motors Ltd': 'EICHERMOT',
  'Eternal Ltd': 'ETERNAL',
  
  // F
  'F A C T': 'FACT',
  'FACT Ltd': 'FACT',
  'Federal Bank': 'FEDERALBNK',
  'Federal Bank Ltd': 'FEDERALBNK',
  'FSN E-Commerce': 'NYKAA',
  'FSN E-Commerce Ventures Ltd': 'NYKAA',
  
  // G
  'GAIL (India)': 'GAIL',
  'GAIL (India) Ltd': 'GAIL',
  'GE Vernova T&D': 'GVT&D',
  'GE Vernova T&D India Ltd': 'GVT&D',
  'General Insuranc': 'GICRE',
  'General Insurance Corp. of India': 'GICRE',
  'Glenmark Pharma.': 'GLENMARK',
  'Glenmark Pharmaceuticals Ltd': 'GLENMARK',
  'GMR Airports': 'GMRAIRPORT',
  'GMR Airports Ltd': 'GMRAIRPORT',
  'Godrej Consumer': 'GODREJCP',
  'Godrej Consumer Products Ltd': 'GODREJCP',
  'Godrej Propert.': 'GODREJPROP',
  'Godrej Properties Ltd': 'GODREJPROP',
  'Grasim Inds': 'GRASIM',
  'Grasim Industries Ltd': 'GRASIM',
  
  // H
  'H P C L': 'HINDPETRO',
  'Hindustan Petroleum Corporation Ltd': 'HINDPETRO',
  'Havells India': 'HAVELLS',
  'Havells India Ltd': 'HAVELLS',
  'HCL Technologies': 'HCLTECH',
  'HCL Technologies Ltd': 'HCLTECH',
  'HDB FINANC SER': 'HDBFS',
  'HDB Financial Services Ltd': 'HDBFS',
  'HDFC AMC': 'HDFCAMC',
  'HDFC AMC Ltd': 'HDFCAMC',
  'HDFC Bank': 'HDFCBANK',
  'HDFC Bank Ltd': 'HDFCBANK',
  'HDFC Life Insur.': 'HDFCLIFE',
  'HDFC Life Insurance Company Ltd': 'HDFCLIFE',
  'Hero Motocorp': 'HEROMOTOCO',
  'Hero MotoCorp Ltd': 'HEROMOTOCO',
  'Hind. Unilever': 'HINDUNILVR',
  'Hindustan Unilever Ltd': 'HINDUNILVR',
  'Hind.Aeronautics': 'HAL',
  'Hindustan Aeronautics Ltd': 'HAL',
  'Hindustan Zinc': 'HINDZINC',
  'Hindustan Zinc Ltd': 'HINDZINC',
  'Hitachi Energy': 'POWERINDIA',
  'Hitachi Energy India Ltd': 'POWERINDIA',
  'Hyundai Motor I': 'HYUNDAI',
  'Hyundai Motor India Ltd': 'HYUNDAI',
  
  // I
  'I O B': 'IOB',
  'Indian Overseas Bank': 'IOB',
  'I O C L': 'IOC',
  'Indian Oil Corporation Ltd': 'IOC',
  'I R C T C': 'IRCTC',
  'Indian Railway Catering & Tourism Corp Ltd': 'IRCTC',
  'I R F C': 'IRFC',
  'Indian Railway Finance Corporation Ltd': 'IRFC',
  'ICICI Bank': 'ICICIBANK',
  'ICICI Bank Ltd': 'ICICIBANK',
  'ICICI Lombard': 'ICICIGI',
  'ICICI Lombard General Insurance Company Ltd': 'ICICIGI',
  'ICICI Pru Life': 'ICICIPRULI',
  'ICICI Prudential Life Insurance Co Ltd': 'ICICIPRULI',
  'IDBI Bank': 'IDBI',
  'IDBI Bank Ltd': 'IDBI',
  'IDFC First Bank': 'IDFCFIRSTB',
  'IDFC First Bank Ltd': 'IDFCFIRSTB',
  'Indian Bank': 'INDIANB',
  'Indian Hotels Co': 'INDHOTEL',
  'Indian Hotels Co Ltd': 'INDHOTEL',
  'Indus Towers': 'INDUSTOWER',
  'Indus Towers Ltd': 'INDUSTOWER',
  'IndusInd Bank': 'INDUSINDBK',
  'IndusInd Bank Ltd': 'INDUSINDBK',
  'Info Edg.(India)': 'NAUKRI',
  'Info Edge (India) Ltd': 'NAUKRI',
  'Infosys': 'INFY',
  'Infosys Ltd': 'INFY',
  'Interglobe Aviat': 'INDIGO',
  'Interglobe Aviation Ltd': 'INDIGO',
  'ITC': 'ITC',
  'ITC Ltd': 'ITC',
  
  // J
  'Jindal Stain.': 'JSL',
  'Jindal Stainless Ltd': 'JSL',
  'Jindal Steel': 'JINDALSTEL',
  'Jindal Steel & Power Ltd': 'JINDALSTEL',
  'Jio Financial': 'JIOFIN',
  'Jio Financial Services Ltd': 'JIOFIN',
  'JSW Energy': 'JSWENERGY',
  'JSW Energy Ltd': 'JSWENERGY',
  'JSW Infrast': 'JSWINFRA',
  'JSW Infrastructure Ltd': 'JSWINFRA',
  'JSW Steel': 'JSWSTEEL',
  'JSW Steel Ltd': 'JSWSTEEL',
  
  // K
  'Kalyan Jewellers': 'KALYANKJIL',
  'Kalyan Jewellers Ltd': 'KALYANKJIL',
  'Kotak Mah. Bank': 'KOTAKBANK',
  'Kotak Mahindra Bank Ltd': 'KOTAKBANK',
  
  // L
  'L&T Finance Ltd': 'LTF',
  'L&T Finance Holdings Ltd': 'LTF',
  'Larsen & Toubro': 'LT',
  'Larsen & Toubro Ltd': 'LT',
  'LG Electronics': 'LGEINDIA',
  'LG Electronics India Ltd': 'LGEINDIA',
  'Life Insurance': 'LICI',
  'Life Insurance Corporation of India': 'LICI',
  'Linde India': 'LINDEINDIA',
  'Linde India Ltd': 'LINDEINDIA',
  'Lloyds Metals': 'LLOYDSME',
  'Lloyds Metals & Energy Ltd': 'LLOYDSME',
  'Lodha Developers': 'LODHA',
  'Lodha Developers Ltd': 'LODHA',
  'LTIMindtree': 'LTIM',
  'LTIMindtree Ltd': 'LTIM',
  'Lupin': 'LUPIN',
  'Lupin Ltd': 'LUPIN',
  
  // M
  'M & M': 'M&M',
  'Mahindra & Mahindra Ltd': 'M&M',
  'Mankind Pharma': 'MANKIND',
  'Mankind Pharma Ltd': 'MANKIND',
  'Marico': 'MARICO',
  'Marico Ltd': 'MARICO',
  'Maruti Suzuki': 'MARUTI',
  'Maruti Suzuki India Ltd': 'MARUTI',
  'Max Financial': 'MFSL',
  'Max Financial Services Ltd': 'MFSL',
  'Max Healthcare': 'MAXHEALTH',
  'Max Healthcare Institute Ltd': 'MAXHEALTH',
  'Mazagon Dock': 'MAZDOCK',
  'Mazagon Dock Shipbuilders Ltd': 'MAZDOCK',
  'Motil.Oswal.Fin.': 'MOTILALOFS',
  'Motilal Oswal Financial Services Ltd': 'MOTILALOFS',
  'Mphasis': 'MPHASIS',
  'Mphasis Ltd': 'MPHASIS',
  'MRF': 'MRF',
  'MRF Ltd': 'MRF',
  'Muthoot Finance': 'MUTHOOTFIN',
  'Muthoot Finance Ltd': 'MUTHOOTFIN',
  
  // N
  'Nestle India': 'NESTLEIND',
  'Nestle India Ltd': 'NESTLEIND',
  'NHPC Ltd': 'NHPC',
  'Nippon Life Ind.': 'NAM-INDIA',
  'Nippon Life India Asset Management Ltd': 'NAM-INDIA',
  'NMDC': 'NMDC',
  'NMDC Ltd': 'NMDC',
  'NTPC': 'NTPC',
  'NTPC Ltd': 'NTPC',
  'NTPC Green Ene.': 'NTPCGREEN',
  'NTPC Green Energy Ltd': 'NTPCGREEN',
  
  // O
  'O N G C': 'ONGC',
  'Oil & Natural Gas Corpn Ltd': 'ONGC',
  'Oberoi Realty': 'OBEROIRLTY',
  'Oberoi Realty Ltd': 'OBEROIRLTY',
  'Oil India': 'OIL',
  'Oil India Ltd': 'OIL',
  'One 97': 'PAYTM',
  'One 97 Communications Ltd': 'PAYTM',
  'Oracle Fin.Serv.': 'OFSS',
  'Oracle Financial Services Software Ltd': 'OFSS',
  
  // P
  'P I Industries': 'PIIND',
  'P I Industries Ltd': 'PIIND',
  'PB Fintech.': 'POLICYBZR',
  'PB Fintech Ltd': 'POLICYBZR',
  'Persistent Systems': 'PERSISTENT',
  'Persistent Systems Ltd': 'PERSISTENT',
  'Phoenix Mills': 'PHOENIXLTD',
  'Phoenix Mills Ltd': 'PHOENIXLTD',
  'Pidilite Inds.': 'PIDILITIND',
  'Pidilite Industries Ltd': 'PIDILITIND',
  'Polycab India': 'POLYCAB',
  'Polycab India Ltd': 'POLYCAB',
  'Power Fin.Corpn.': 'PFC',
  'Power Finance Corporation Ltd': 'PFC',
  'Power Grid Corpn': 'POWERGRID',
  'Power Grid Corporation of India Ltd': 'POWERGRID',
  'Prestige Estates': 'PRESTIGE',
  'Prestige Estates Projects Ltd': 'PRESTIGE',
  'Punjab Natl.Bank': 'PNB',
  'Punjab National Bank': 'PNB',
  
  // R
  'Rail Vikas': 'RVNL',
  'Rail Vikas Nigam Ltd': 'RVNL',
  'REC Ltd': 'RECLTD',
  'Reliance Industr': 'RELIANCE',
  'Reliance Industries Ltd': 'RELIANCE',
  
  // S
  'S A I L': 'SAIL',
  'Steel Authority of India Ltd': 'SAIL',
  'Samvardh. Mothe.': 'MOTHERSON',
  'Samvardhana Motherson International Ltd': 'MOTHERSON',
  'SBI': 'SBIN',
  'State Bank of India': 'SBIN',
  'SBI Cards': 'SBICARD',
  'SBI Cards & Payment Services Ltd': 'SBICARD',
  'SBI Life Insuran': 'SBILIFE',
  'SBI Life Insurance Company Ltd': 'SBILIFE',
  'Schaeffler India': 'SCHAEFFLER',
  'Schaeffler India Ltd': 'SCHAEFFLER',
  'Shree Cement': 'SHREECEM',
  'Shree Cement Ltd': 'SHREECEM',
  'Shriram Finance': 'SHRIRAMFIN',
  'Shriram Finance Ltd': 'SHRIRAMFIN',
  'Siemens': 'SIEMENS',
  'Siemens Ltd': 'SIEMENS',
  'Solar Industries': 'SOLARINDS',
  'Solar Industries India Ltd': 'SOLARINDS',
  'SRF': 'SRF',
  'SRF Ltd': 'SRF',
  'Sun Pharma.Inds.': 'SUNPHARMA',
  'Sun Pharmaceutical Industries Ltd': 'SUNPHARMA',
  'Suzlon Energy': 'SUZLON',
  'Suzlon Energy Ltd': 'SUZLON',
  'Swiggy': 'SWIGGY',
  'Swiggy Ltd': 'SWIGGY',
  
  // T
  'Tata Capital': 'TATACAP',
  'Tata Capital Ltd': 'TATACAP',
  'Tata Comm': 'TATACOMM',
  'Tata Communications Ltd': 'TATACOMM',
  'Tata Consumer': 'TATACONSUM',
  'Tata Consumer Products Ltd': 'TATACONSUM',
  'Tata Motors': 'TATAMOTORS',
  'Tata Motors Ltd': 'TATAMOTORS',
  'Tata Motors Passenger Vehicles Ltd': 'TMPV',
  'Tata Power Co.': 'TATAPOWER',
  'Tata Power Company Ltd': 'TATAPOWER',
  'Tata Steel': 'TATASTEEL',
  'Tata Steel Ltd': 'TATASTEEL',
  'TCS': 'TCS',
  'Tata Consultancy Services Ltd': 'TCS',
  'Tech Mahindra': 'TECHM',
  'Tech Mahindra Ltd': 'TECHM',
  'Titan Company': 'TITAN',
  'Titan Company Ltd': 'TITAN',
  'Torrent Pharma.': 'TORNTPHARM',
  'Torrent Pharmaceuticals Ltd': 'TORNTPHARM',
  'Torrent Power': 'TORNTPOWER',
  'Torrent Power Ltd': 'TORNTPOWER',
  'Trent': 'TRENT',
  'Trent Ltd': 'TRENT',
  'Tube Investments': 'TIINDIA',
  'Tube Investments of India Ltd': 'TIINDIA',
  'TVS Motor Co.': 'TVSMOTOR',
  'TVS Motor Company Ltd': 'TVSMOTOR',
  
  // U
  'UltraTech Cem.': 'ULTRACEMCO',
  'UltraTech Cement Ltd': 'ULTRACEMCO',
  'Union Bank (I)': 'UNIONBANK',
  'Union Bank of India': 'UNIONBANK',
  'United Spirits': 'UNITDSPR',
  'United Spirits Ltd': 'UNITDSPR',
  'Uno Minda': 'UNOMINDA',
  'Uno Minda Ltd': 'UNOMINDA',
  'UPL': 'UPL',
  'UPL Ltd': 'UPL',
  
  // V
  'Varun Beverages': 'VBL',
  'Varun Beverages Ltd': 'VBL',
  'Vedanta': 'VEDL',
  'Vedanta Ltd': 'VEDL',
  'Vishal Mega Mart': 'VMM',
  'Vishal Mega Mart Ltd': 'VMM',
  'Vodafone Idea': 'IDEA',
  'Vodafone Idea Ltd': 'IDEA',
  
  // W
  'Waaree Energies': 'WAAREEENER',
  'Waaree Energies Ltd': 'WAAREEENER',
  'Wipro': 'WIPRO',
  'Wipro Ltd': 'WIPRO',
  
  // Y
  'Yes Bank': 'YESBANK',
  'Yes Bank Ltd': 'YESBANK',
  
  // Z
  'Zydus Lifesci.': 'ZYDUSLIFE',
  'Zydus Lifesciences Ltd': 'ZYDUSLIFE'
};
