// Company name to ticker symbol mapping for Screener.in URLs
// Add more mappings as you find the ticker symbols for each company
// Format: 'Company Name': 'TICKER'

export const companyTickerMap = {
  'Bharti Airtel': 'BHARTIARTL',
  'Bharti Airtel Ltd': 'BHARTIARTL',
  'Reliance Industries': 'RELIANCE',
  'Tata Consultancy Services': 'TCS',
  'HDFC Bank': 'HDFCBANK',
  'ICICI Bank': 'ICICIBANK',
  'Infosys': 'INFY',
  'Hindustan Unilever': 'HINDUNILVR',
  'ITC': 'ITC',
  'State Bank of India': 'SBIN',
  'Bharti Hexacom': 'BHARTIHEXA',
  'Axis Bank': 'AXISBANK',
  'Kotak Mahindra Bank': 'KOTAKBANK',
  'Larsen & Toubro': 'LT',
  'Asian Paints': 'ASIANPAINT',
  'Bajaj Finance': 'BAJFINANCE',
  'Bajaj Finserv': 'BAJAJFINSV',
  'Bajaj Auto': 'BAJAJ-AUTO',
  'HCL Technologies': 'HCLTECH',
  'Wipro': 'WIPRO',
  'Sun Pharmaceutical': 'SUNPHARMA',
  'Nestle India': 'NESTLEIND',
  'Titan Company': 'TITAN',
  'UltraTech Cement': 'ULTRACEMCO',
  'Mahindra & Mahindra': 'M&M',
  'Maruti Suzuki': 'MARUTI',
  'Tata Motors': 'TATAMOTORS',
  'Tata Steel': 'TATASTEEL',
  'JSW Steel': 'JSWSTEEL',
  'Adani Enterprises': 'ADANIENT',
  'Adani Ports': 'ADANIPORTS',
  'Adani Green Energy': 'ADANIGREEN',
  'Adani Power': 'ADANIPOWER',
  'Adani Total Gas': 'ATGL',
  'Adani Energy Solutions': 'ADANIENSOL',
  'Coal India': 'COALINDIA',
  'NTPC': 'NTPC',
  'Power Grid': 'POWERGRID',
  'Oil and Natural Gas': 'ONGC',
  'Indian Oil': 'IOC',
  'Bharat Petroleum': 'BPCL',
  'Hindustan Petroleum': 'HINDPETRO',
  'Gail India': 'GAIL',
  'DLF': 'DLF',
  'Godrej Properties': 'GODREJPROP',
  'Prestige Estates': 'PRESTIGE',
  'Britannia Industries': 'BRITANNIA',
  'Dabur India': 'DABUR',
  'Colgate-Palmolive': 'COLPAL',
  'Apollo Hospitals': 'APOLLOHOSP',
  'Dr Reddy\'s Laboratories': 'DRREDDY',
  'Cipla': 'CIPLA',
  'Aurobindo Pharma': 'AUROPHARMA',
  'Lupin': 'LUPIN',
  'Torrent Pharmaceuticals': 'TORNTPHARM',
  'Divis Laboratories': 'DIVISLAB',
  'Bharat Electronics': 'BEL',
  'Bharat Forge': 'BHARATFORG',
  'Bosch': 'BOSCHLTD',
  'Eicher Motors': 'EICHERMOT',
  'Hero MotoCorp': 'HEROMOTOCO',
  'TVS Motor': 'TVSMOTOR',
  'Ashok Leyland': 'ASHOKLEY',
  'Bharat Heavy Electricals': 'BHEL',
  'Siemens': 'SIEMENS',
  'ABB India': 'ABB',
  'Schneider Electric': 'SCHNEIDER',
  'Cummins India': 'CUMMINSIND',
  'Ambuja Cements': 'AMBUJACEM',
  'ACC': 'ACC',
  'Shree Cement': 'SHREECEM',
  'Dalmia Bharat': 'DALBHARAT',
  'Ramco Cements': 'RAMCOCEM',
  'Grasim Industries': 'GRASIM',
  'Aditya Birla Capital': 'ABCAPITAL',
  'Canara Bank': 'CANBK',
  'Bank of Baroda': 'BANKBARODA',
  'Punjab National Bank': 'PNB',
  'Union Bank of India': 'UNIONBANK',
  'Bank of India': 'BANKINDIA',
  'IDBI Bank': 'IDBIGOLD',
  'AU Small Finance Bank': 'AUBANK',
  'Berger Paints': 'BERGEPAINT',
  'Kansai Nerolac': 'KANSAINER',
  'Indigo Paints': 'INDIGOPNTS',
  'Avenue Supermarts': 'DMART',
  'Trent': 'TRENT',
  'Tata Consumer Products': 'TATACONSUM',
  'Varun Beverages': 'VBL',
  'United Spirits': 'MCDOWELL-N',
  'Radico Khaitan': 'RADICO',
  'Godrej Consumer': 'GODREJCP',
  'Marico': 'MARICO',
  'Emami': 'EMAMILTD',
  'Page Industries': 'PAGEIND',
  
  // Add more mappings below - match exact company names from your data
  // To find ticker: Go to Screener.in, search for company, check URL
  // Example: Search "Bharti Airtel" → URL: /company/BHARTIARTL/consolidate/ → Ticker: 'BHARTIARTL'
  
  // Common companies from your data (add tickers as you find them):
  'A B B': 'ABB',
  'Abbott India': 'ABBOTINDIA',
  'Adani Energy Sol': 'ADANIENSOL',
  'Adani Enterp.': 'ADANIENT',
  'Adani Green': 'ADANIGREEN',
  'Adani Ports': 'ADANIPORTS',
  'Adani Power': 'ADANIPOWER',
  'Adani Total Gas': 'ATGL',
  'Aditya Birla Cap': 'ABCAPITAL',
  'Alkem Lab': 'ALKEM',
  'Ambuja Cements': 'AMBUJACEM',
  'Apollo Hospitals': 'APOLLOHOSP',
  'Ashok Leyland': 'ASHOKLEY',
  'Asian Paints': 'ASIANPAINT',
  'AU Small Finance': 'AUBANK',
  'Aurobindo Pharma': 'AUROPHARMA',
  'Avenue Super.': 'DMART',
  'Axis Bank': 'AXISBANK',
  'B H E L': 'BHEL',
  'B P C L': 'BPCL',
  'Bajaj Auto': 'BAJAJ-AUTO',
  'Bajaj Finance': 'BAJFINANCE',
  'Bajaj Finserv': 'BAJAJFINSV',
  'Bajaj Holdings': 'BAJAJHLDNG',
  'Bajaj Housing': 'BAJAJHLDNG',
  'Bank of Baroda': 'BANKBARODA',
  'Bank of India': 'BANKINDIA',
  'Berger Paints': 'BERGEPAINT',
  'Bharat Dynamics': 'BDL',
  'Bharat Electron': 'BEL',
  'Bharat Forge': 'BHARATFORG',
  'Bharti Hexacom': 'BHARTIHEXA',
  'Bosch': 'BOSCHLTD',
  'Britannia Inds.': 'BRITANNIA',
  'BSE': 'BSE',
  'Canara Bank': 'CANBK',
  'CG Power & Ind': 'CGPOWER',
  'Cholaman.Inv.&Fn': 'CHOLAFIN',
  'Cipla': 'CIPLA',
  'Coal India': 'COALINDIA',
  'Coforge': 'COFORGE',
  'Colgate-Palmoliv': 'COLPAL',
  'Coromandel Inter': 'COROMANDEL',
  'Cummins India': 'CUMMINSIND',
  'Dabur India': 'DABUR',
  'Dixon Technolog.': 'DIXON',
  'DLF': 'DLF',
  'Dr Reddy\'s Labs': 'DRREDDY',
  'Eicher Motors': 'EICHERMOT',
  // Add more mappings as you find the ticker symbols...
}

